dashboard/dashapp/urls.py
#### For File Upload
from django.conf import settings
from django.conf.urls.static import static
## End
from django.urls import path
from . import views
from dashapp.tokenleader import tlviews
from dashapp.linkinv import  linkinv_views
from dashapp.views import paperhouse_delete_invoice
from dashapp.paperhouse import paperhouse
from dashapp.penman import penman
from dashapp.telegraph import telegraph
from dashapp.flexflow import flexflow
#from rest_framework_swagger.views import get_swagger_view
#from rest_framework.documentation import include_docs_urls

#schema_view = get_swagger_view(title='TSP Billing')
app_name = 'dashapp'
urlpatterns = [path('', views.login, name='login'),
               path('logout', views.log_out, name='logout'),
               path('signout', views.log_out, name='signout'),
    #Infops DB
    path('home2', views.home2, name='home2'),
    
    path('list_links', views.list_links, name='list_links'),
    path('list_ravl_obj/<slug:objname>/<slug:rolename>', linkinv_views.list_ravl_obj, name='list_ravl_obj'),
    path('delete_ravl/<slug:objname>/<slug:objid>', linkinv_views.delete_ravl, name='delete_ravl'),
    path('managelocalnet', views.managelocalnet, name='managelocalnet'),
    path('add_address', linkinv_views.add_address, name='add_address'),
    path('add_rate', linkinv_views.add_rate,  name='add_rate'),
    path('add_payment', linkinv_views.add_payment,  name='add_payment'),
    
    
    path('list_test', views.list_links, name='list_test'),      
    #Token Leader
    path('add_org', views.add_org, name='add_org'),
    path('list_org', views.list_org, name='list_org'),
    path('delete_org', views.delete_org, name='delete_org'),
    path('add_ou', views.add_ou, name='add_ou'),
    path('list_ou', views.list_ou, name='list_ou'),
    path('delete_ou', views.delete_ou, name='delete_ou'),
    path('add_dept', views.add_dept, name='add_dept'),
    path('list_dept', views.list_dept, name='list_dept'),
    path('delete_dept', views.delete_dept, name='delete_dept'),
    path('add_wfc', views.add_wfc, name='add_wfc'),
    path('list_wfc', views.list_wfc, name='list_wfc'),
    path('delete_wfc', views.delete_wfc, name='delete_wfc'),
    path('add_role', views.add_role, name='add_role'),
    path('list_role', views.list_role, name='list_role'),
    path('delete_role', views.delete_role, name='delete_role'),
    path('adduser', views.adduser, name='adduser'),
    path('list_users', views.list_users, name='list_users'),
    path('adduser', views.adduser, name='adduser'),
    path('delete_user', views.delete_user, name='delete_user'),
    path('change_password', tlviews.change_password, name='change_password'),
    path('reset_password/<slug:username>/<slug:domain>', tlviews.reset_password, name='reset_password'),
    path('unlock_user/<slug:username>/<slug:domain>', tlviews.unlock_user, name='unlock_user'),
    
    path('list_service', views.list_service, name='list_service'),
    path('add_service', views.add_service, name='add_service'),
    path('delete_service', views.delete_service, name='delete_service'),
    
  
    
    #XLuploader
    
    #path('xluploader_invoice_upload', views.xluploader_invoice_upload, name='xluploader_invoice_upload'),
    path('download_invoicexlformat', views.download_invoicexlformat, name='download_invoicexlformat'),
        
    
    #penman
    path('penman_list_events', penman.list_events, name='penman_list_events'),
    path('penman_delete_events', views.penman_delete_events, name='penman_delete_events'),
    path('delete_event', views.penman_delete_event, name='delete_event'),       
    #paperhouse
    path('paperhouse_list_invoice/<slug:invoicenum>/<slug:mode>/<slug:listype>', 
         views.paperhouse_list_invoice, name='paperhouse_list_invoice'),   
    path('paperhouse_delete_invoice', views.paperhouse_delete_invoice, name='paperhouse_delete_invoice'),    
    path('tsp_list_invoice', views.tsp_list_invoice, name='tsp_list_invoice'),
    path('paperhouse_savedraft_list/<slug:status>', 
         paperhouse.draft_list, name='paperhouse_savedraft_list'),   
    #striker
    path('striker_list_responces/<slug:request_id>', views.striker_list_responces, name='striker_list_responces'),
    path('striker_delete_responces', views.striker_delete_responces, name='striker_delete_responces'),
    path('striker_update_Invoice/<slug:actionrole>', views.striker_update_Invoice, name='striker_update_Invoice'),
    path('striker_update_from_draft/<slug:actionrole>', views.striker_update_from_Draft, name='striker_update_from_draft'),
    
    
    #,path('swagger-docs/', schema_view)
    #,path('docs/', include_docs_urls(title='TSP Billing'))
    
    path('manageaddress', views.manageaddress, name='manageaddress'),
    path('managerate', views.managerate, name='managerate'),
    path('managepayment', views.managepayment, name='managepayment'),
    path('listobjects', views.listobjects, name='listobjects'),
    
    path('listdocs', views.listdocs, name='listdocs'),
    path('list_mailmap_by_status/<slug:status_name>', telegraph.list_mailmap, name='list_mailmap_by_status'),
    path('list_mailmap_by_docid/<slug:docid>', telegraph.list_mailmap, name='list_mailmap_by_docid'),
    path('create_mailmap', telegraph.create_mailmap, name='create_mailmap'),
    path('delete_mailmap/<slug:status_name>', telegraph.delete_mailmap, name='delete_mailmap'),
    path('update_mailmap/<slug:status_name>', telegraph.update_mailmap, name='update_mailmap'),
    
    path('add_wfmobj/<slug:objname>', flexflow.add_wfmobj, name='add_wfmobj'),
    path('list_wfmobj/<slug:objname>', flexflow.list_wfmobj, name='list_wfmobj'),
    path('delete_wfmobj/<slug:objname>/<slug:filter_by_name>', flexflow.delete_wfmobj, name='delete_wfmobj'),
    path('update_wfmobj/<slug:objname>/<slug:filter_by_name>', flexflow.update_wfmobj, name='update_wfmobj'),
    
    path('create_wfdoc/<slug:doctype>', flexflow.create_wfdoc, name='create_wfdoc'),
    path('xluploader_invoice_upload/<slug:wfdoctype>', flexflow.xl_upload, name='xluploader_invoice_upload'),
    path('list_wfdoc/<slug:doctype>', flexflow.list_wfdoc, name='list_wfdoc'),
    path('list_drafts/<slug:doctype>', flexflow.list_drafts, name='list_drafts'),
    path('update_wfdoc/<slug:filter_by_name>', flexflow.update_wfdoc, name='update_wfdoc'),
    path('list_doctypes', flexflow.list_doctypes, name='list_doctypes'),
    path('update_from_draft/<slug:filter_by_name>', flexflow.update_from_draft, name='update_from_draft'),
    path('filtered_list_drafts/<slug:doctype>/<slug:status_name_filter>', flexflow.list_drafts, name='filtered_list_drafts'),
    path('update_selected_fm_drafts', flexflow.update_selected_fm_draft, name='update_selected_fm_drafts'),
    ]



#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/dashboard/urls.py
from django.contrib import admin
from django.urls import path , include
#from rest_framework_swagger.views import get_swagger_view
#from rest_framework.documentation import include_docs_urls

#schema_view = get_swagger_view(title='TSP Billing')



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashapp.urls')),
    #path(r'swagger-docs/', schema_view),
    #path(r'docs/', include_docs_urls(title='TSP Billing')),
]

dashboard/dashapp/models.py
from django.db import models

# Create your models here.

dashboard/dashapp/views.py
import os
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from tokenleaderclient.configs.config_handler import Configs    
from tokenleaderclient.client.client import Client 
from micros1client.client   import MSClient
from linkinvclient.client import LIClient
from django.views.generic.edit import FormView
#from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy
#File Storage
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from werkzeug.utils import secure_filename

from dashapp.tokenleader import tllogin
from dashapp.linkinv import linkinv_views as linkv
from dashapp.tokenleader import tlviews

from dashapp.xluploader import tspinv as xluploadertspinv

from dashapp.penman import penman
from dashapp.paperhouse import paperhouse
from dashapp.striker import striker


def login(request):
    result = tllogin.login(request)
    return result

def log_out(request):
    print("i m inside lout out view")
    template_name, template_data  = tllogin.logout(request)
    return render(request, template_name, template_data)
    
# def home(request):
#     session_user_details = request.session.get('session_user_details')
#     template_data = {"user_details": session_user_details }   
#     result = render(request, 'home.html', template_data)            
#     return result
 
def list_links(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.list_links(request)
    return result
    
def managepayment(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.managepayment(request)
    return result

def managerate(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.managerate(request)
    return result

def manageaddress(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.manageaddress(request)
    return result

def managelocalnet(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.managelocalnet(request)
    return result

def listobjects(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.listobjects(request)
    return result

# TOKENLEADER ======================================

def list_org(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_org(request)
    return result
    		
def add_org(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_org(request)
    return result
    		
def delete_org(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_org(request)
    return result       			

def list_ou(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_ou(request)
    return result

def add_ou(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_ou(request)
    return result   
    		
def delete_ou(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_ou(request)
    return result    

def list_dept(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_dept(request)
    return result
    		
def add_dept(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_dept(request)
    return result
    		    		
def delete_dept(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_dept(request)
    return result  
    		
def list_role(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_role(request)
    return result

def add_role(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_role(request)
    return result
    		
def delete_role(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_role(request)
    return result


def list_users(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_users(request)
    return result

def adduser(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.adduser(request)
    return result
    		
def delete_user(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_user(request)
    return result
    		
def list_wfc(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_wfc(request)
    return result

def add_wfc(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_wfc(request)
    return result
    		
def delete_wfc(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_wfc(request)
    return result
    		
# TOKENLEADER ===========================================



### Divisional Invoice Functionality END
      




def add_service(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_service(request)    
    return result

def list_service(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_service(request)    
    return result

def delete_service(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_service(request)    
    return result


def list_test(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.list_test(request)  

def home2(request):
    result = render(request, 'home3.html')
    return result

#### Log out
def logout(request):
    if request.session.has_key('uname'):
        del request.session['uname']
    if request.session.has_key('psword'):
        del request.session['psword']
    request.session.clear_expired() 
    result = tllogin.login(request)
    return result
    #result = render(request, "login.html", {'SESSION_EXPIRE':'TRUE'})
    #return result  

######Invoice Model Form Testing
def add_model(request):
 
    if request.method == "POST":
        form = invoiceForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/') 
    else: 
        form = invoiceForm() 
        return render(request, "home.html", {'CREATE_INVOICE_FORM': form})

 
############### Xluploader #########################################


def xluploader_invoice_upload(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = xluploadertspinv.invoice_upload(request)    
    return result

def download_invoicexlformat(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = xluploadertspinv.download_invoicexlformat(request)    
    return result


############################# PEN and PAPER House#######################################

def penman_list_events(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = penman.list_events(request)
    return result

def penman_delete_events(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = penman.delete_events(request)
    return result


def penman_delete_event(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = penman.delete_event(request)
    return result



def paperhouse_list_invoice(request, invoicenum, mode, listype):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
        if listype == 'admin':
            result = paperhouse.list_invoices(request, invoicenum, mode, 'admin')
        else:
            result = paperhouse.list_invoices(request, invoicenum, mode)
    return result

# def paperhouse_list_invoice_admin(request):
#     if 'uname' not in request.session :
#       result = login(request)
#     elif 'uname' in request.session :
#       result = paperhouse.list_invoices(request, "admin")
#     return result 

def paperhouse_delete_invoice(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = paperhouse.delete_invoices(request)
    return result

def tsp_list_invoice(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = paperhouse.tsp_list_invoices(request)
    return result


def striker_list_responces(request, request_id):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = striker.list_exec_status(request, request_id)
    return result


def striker_delete_responces(request):
    if 'uname' not in request.session :

dashboard/dashapp/templates/home.html
{% load i18n %}
{% load l10n %}
{% load static %}
{% static "dashapp/images/automated-invoice-processing.jpeg" as photo1 %}
{% static "dashapp/images/invoice-pic.jpeg" as photo2 %}
{% static "dashapp/images/workflow_chart.jpg" as workflow_chart %}
{% static "dashapp/images/Utility-Bill-Processing-Services-617x260.jpg" as photo3 %}
{% static "dashapp/styles/edit_form.css" as edit_format %}
{% static "dashapp/styles/xlupload_page_format.css" as xlupload_page_format %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} INFO-OPS INVOICE PROCESSING SYSTEM {% endblock  %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ edit_format}}">
    <link rel="stylesheet" href="{{ xlupload_page_format}}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> 
    
   
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
   
	 
 
  
</head>


<body>
    
    <div class="container">
    {% block navigation_bar %}
        {% include "navbar/navigation_bar.html" %}
    {% endblock navigation_bar %}
    </div>
    
    <br><br>
    
    <div class="container-fluid py-1"  style="background-image: url('{{ photo2 }}'); 
                           opacity:0.4" >
        <h3 class="display text-center font-weight-bold" style="color:green">
                     Info-ops Invoice Processing System</h3>
                     
    </div>
      
    
    <div class="container-fluid ">  
        {% block content-area %}  
        <div align=center>   
         <img  src="{{ workflow_chart }}" alt="Smiley face" height="400px" width="70%">
              </div><br><br><br>
        {% endblock content-area %}
    </div>
    
</body>

</html>



<!--  

  {'email': 'user1', 'allowemaillogin': 'N', 
  'wfc': {'name': 'wfc1', 'orgunit': 'ou1', 'department': 'dept1', 
          'id': 1, 'creation_date': '2019-07-04 15:03:08', 'org': 'org1', 
          'created by': None, 'is_active': 'Y'}, 
   'roles': ['role1'], 
   'username': 'user1', 
   'id': 1, 'creation_date': '2019-07-04 15:04:09', 
   'otp_mode': '', 'created by': None, 'is_active': 'Y'}
-->
   
   <!--   <div id="sidebar" class="row">
    {% block sidebar %}   {% endblock %}
    </div> -->
    

dashboard/dashapp/templates/login.html
{% load i18n %}
{% load l10n %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
	<title>TSP Billing | Login</title>
	<meta charset="UTF-8">	 
 	<link rel='stylesheet' type='text/css' href='{% static "dashapp/css/util.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "dashapp/css/main.css" %}'>

</head>
<body>

    <div class="limiter">
        <div class="imgcontainer">
            
        </div>
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-form-title" style="background-image: url('{% static 'dashapp/images/bg-01.jpg' %}');">
                <span class="login100-form-title-1">
                    Sign In
                </span>
            </div>
            <div class="login-result">
                         {{ mykey }}
                         </div>

                <form class="login100-form validate-form" action="{% url 'dashapp:login' %}"  method="post">
                {% csrf_token %} 
                    <div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
                        <span class="label-input100">Username</span>
                        <input class="input100" type="text" name="username" placeholder="Enter username">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="wrap-input100 validate-input m-b-18" data-validate="Password is required">
                        <span class="label-input100">Password</span>
                        <input class="input100" type="password" name="password" placeholder="Enter password">
                        <span class="focus-input100"></span>
                    </div>
                    
                     <div class="wrap-input100 m-b-18" >
                        <span class="label-input100">Domain</span>
                        <input class="input100" type="text" name="domain" placeholder="Enter Domain">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="flex-sb-m w-full p-b-30">
                        <div class="contact100-form-checkbox">
                            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                            <label class="label-checkbox100" for="ckb1">
                                Remember me
                            </label>
                        </div>

                        <div>
                            <a href="#" class="txt1">
                                Forgot Password?
                            </a>
                        </div>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Login
                        </button>
                    </div>
                    <br> <br> <br> <br> 
                    <div class="login-result">
						 {{ mykey }}
						 </div>
                </form>
               
            </div>
        </div>
    </div>
    
</body>
</html>

dashboard/dashapp/templates/login_otp.html
{% load i18n %}
{% load l10n %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
	<title>TSP Billing | Login</title>
	<meta charset="UTF-8">	 
 	<link rel='stylesheet' type='text/css' href='{% static "dashapp/css/util.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "dashapp/css/main.css" %}'>

</head>
<body>

    <div class="limiter">
        <div class="imgcontainer">
            
        </div>
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-form-title" style="background-image: url('{% static 'dashapp/images/bg-01.jpg' %}');">
                <span class="login100-form-title-1">
                    Sign In
                </span>
            </div>

                <form class="login100-form validate-form" action="{% url 'dashapp:login' %}"  method="post">
                {% csrf_token %} 
                    <div  >
                        <input  type="hidden" name="username" value= {{ uname }} >
                    </div>
                    
                    <div  >
                        <input class="input100" type="hidden" name="domain" value= {{ domain }} >
                    </div>
                    
                     <div class="wrap-input100 m-b-18" >
                        <span class="label-input100">OTP</span>
                        <input class="input100" type="text" name="otp" placeholder="Enter OTP">
                        <span class="focus-input100"></span>
                    </div>

                   
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Login
                        </button>
                    </div>
                    <br> <br> <br> <br> 
                    <div class="login-result">
						 {{ mykey }}
						 </div>
                </form>
               
            </div>
        </div>
    </div>
    
</body>
</html>

dashboard/dashapp/templates/nav_dropdown_admin.html
{% url 'dashapp:list_users' as luser %}
{% url 'dashapp:list_org' as lorg %}
{% url 'dashapp:list_dept' as ldept %}
{% url 'dashapp:list_role' as lrole %}
{% url 'dashapp:list_ou' as lou %}
{% url 'dashapp:list_wfc' as lwfc %}
{% url 'dashapp:list_service' as lservice %}
	  <ul class="navbar-nav py-0"> 
		    <!-- User Admin  -->
            <li class="nav-item dropdown py-0">
              <a class="nav-link dropdown-toggle fas fa-tools" href="#" id="navbardrop" data-toggle="dropdown">
                Settings
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{{ luser }}">Manage Users</a>
                <a class="dropdown-item" href="{{ lorg }}">Manage Org</a>
                <a class="dropdown-item" href="#">Link 3</a>
              </div>
            </li>
		    
		   <!-- Invoice  -->
	          <li class="nav-item dropdown py-0">
	            <a class="nav-link dropdown-toggle fas fa-tasks" href="#" id="navbardrop" data-toggle="dropdown">
	              Invoices
	            </a>
	            <div class="dropdown-menu">
	              <a class="dropdown-item" href="#">Link 1</a>
	              <a class="dropdown-item" href="#">Link 2</a>
	              <a class="dropdown-item" href="#">Link 3</a>
	            </div>
	          </li> 
	          
	        <!-- Links -->
              <li class="nav-item dropdown py-0">
                <a class="nav-link dropdown-toggle fas fa-satellite-dish" href="#" id="navbardrop" data-toggle="dropdown">
                  Links
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Link 1</a>
                  <a class="dropdown-item" href="#">Link 2</a>
                  <a class="dropdown-item" href="#">Link 3</a>
                </div>
              </li> 
              
              <!-- Financial -->
              <li class="nav-item dropdown py-0">
                <a class="nav-link dropdown-toggle fas fa-calculator" href="#" id="navbardrop" data-toggle="dropdown">
                  Financial
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Link 1</a>
                  <a class="dropdown-item" href="#">Link 2</a>
                  <a class="dropdown-item" href="#">Link 3</a>
                </div>
              </li> 
        </ul>
  
       

		  

dashboard/dashapp/templates/navigation_bar.html
{% block navigation_bar %}
{% url 'dashapp:logout' as logout %}
 <nav class="navbar navbar-expand-sm bg-dark py-0 navbar-dark fixed-top py-my-0"  > 
     
    <a class="navbar-brand py-0 fas fa-home" style='font-size:20px;color:red' href="/">InfoVoice</a>
    
    <div class="container">
	    {% if "role1"  in user_details.roles %}       
		   {% include "nav_dropdown_admin.html" %}
		{% elif "TSP" in user_details.roles %}
		   {% include "nav_dropdown_tsp.html" %}
		{% elif "MIS" in user_details.roles %}
	       {% include "nav_dropdown_mis.html" %}
	    {% else  %}
	       <div class="nav-text  text-info" >
	           No action for role {{ user_details.roles|join:"," }}
	       </div>
	    {% endif %}
    </div>
	
    <div class="container justify-content-center">
	    <div class="nav-text  text-warning py-0
	        font-weight-bolder" style="font-family:Impact">
	        <h1>InfoVoice</h1>
	    </div>
    </div>
     
    <div class="container justify-content-end">  
	    <ul class="navbar-nav  py-0">
	       <li class="nav-item dropdown py-0">
	          <a class="nav-link dropdown-toggle fas fa-user"  id="navbardrop" data-toggle="dropdown" 
	          href="#" style='color: lime'>
	             {{ user_details.username }}
	          </a>
	             <div class="dropdown-menu">
	                <p class="dropdown-item">{{ user_details.wfc.org }}</p>
	                <p class="dropdown-item">{{ user_details.email }}</p>
	                <p class="dropdown-item">{{ user_details.roles|join:"," }}</p>	                
	                <a class="dropdown-item" href="{{ logout }}">log out</a>
	             </div> 
	       </li>
	    </ul>
    </div>        
   
</nav>
{% endblock navigation_bar %}
		  

dashboard/dashapp/templates/simple+upload.html
 
{% load static %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
</form>

  {% if uploaded_file_url %}
<p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

<p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}