dashboard/dashapp/urls.py
#### For File Upload
from django.conf import settings
from django.conf.urls.static import static
## End
from django.urls import path
from . import views
from dashapp.tokenleader import tlviews
from dashapp.linkinv import  linkinv_views
from dashapp.views import paperhouse_delete_invoice
from dashapp.paperhouse import paperhouse
from dashapp.penman import penman
from dashapp.telegraph import telegraph
from dashapp.flexflow import flexflow
#from rest_framework_swagger.views import get_swagger_view
#from rest_framework.documentation import include_docs_urls

#schema_view = get_swagger_view(title='TSP Billing')
app_name = 'dashapp'
urlpatterns = [path('', views.login, name='login'),
               path('logout', views.log_out, name='logout'),
               path('signout', views.log_out, name='signout'),
    #Infops DB
    path('home2', views.home2, name='home2'),
    
    path('list_links', views.list_links, name='list_links'),
    path('list_ravl_obj/<slug:objname>/<slug:rolename>', linkinv_views.list_ravl_obj, name='list_ravl_obj'),
    path('delete_ravl/<slug:objname>/<slug:objid>', linkinv_views.delete_ravl, name='delete_ravl'),
    path('managelocalnet', views.managelocalnet, name='managelocalnet'),
    path('add_address', linkinv_views.add_address, name='add_address'),
    path('add_rate', linkinv_views.add_rate,  name='add_rate'),
    path('add_payment', linkinv_views.add_payment,  name='add_payment'),
    
    
    path('list_test', views.list_links, name='list_test'),      
    #Token Leader
    path('add_org', views.add_org, name='add_org'),
    path('list_org', views.list_org, name='list_org'),
    path('delete_org', views.delete_org, name='delete_org'),
    path('add_ou', views.add_ou, name='add_ou'),
    path('list_ou', views.list_ou, name='list_ou'),
    path('delete_ou', views.delete_ou, name='delete_ou'),
    path('add_dept', views.add_dept, name='add_dept'),
    path('list_dept', views.list_dept, name='list_dept'),
    path('delete_dept', views.delete_dept, name='delete_dept'),
    path('add_wfc', views.add_wfc, name='add_wfc'),
    path('list_wfc', views.list_wfc, name='list_wfc'),
    path('delete_wfc', views.delete_wfc, name='delete_wfc'),
    path('add_role', views.add_role, name='add_role'),
    path('list_role', views.list_role, name='list_role'),
    path('delete_role', views.delete_role, name='delete_role'),
    path('adduser', views.adduser, name='adduser'),
    path('list_users', views.list_users, name='list_users'),
    path('adduser', views.adduser, name='adduser'),
    path('delete_user', views.delete_user, name='delete_user'),
    path('change_password', tlviews.change_password, name='change_password'),
    path('reset_password/<slug:username>/<slug:domain>', tlviews.reset_password, name='reset_password'),
    path('unlock_user/<slug:username>/<slug:domain>', tlviews.unlock_user, name='unlock_user'),
    
    path('list_service', views.list_service, name='list_service'),
    path('add_service', views.add_service, name='add_service'),
    path('delete_service', views.delete_service, name='delete_service'),
    
  
    
    #XLuploader
    
    #path('xluploader_invoice_upload', views.xluploader_invoice_upload, name='xluploader_invoice_upload'),
    path('download_invoicexlformat', views.download_invoicexlformat, name='download_invoicexlformat'),
        
    
    #penman
    path('penman_list_events', penman.list_events, name='penman_list_events'),
    path('penman_delete_events', views.penman_delete_events, name='penman_delete_events'),
    path('delete_event', views.penman_delete_event, name='delete_event'),       
    #paperhouse
    path('paperhouse_list_invoice/<slug:invoicenum>/<slug:mode>/<slug:listype>', 
         views.paperhouse_list_invoice, name='paperhouse_list_invoice'),   
    path('paperhouse_delete_invoice', views.paperhouse_delete_invoice, name='paperhouse_delete_invoice'),    
    path('tsp_list_invoice', views.tsp_list_invoice, name='tsp_list_invoice'),
    path('paperhouse_savedraft_list/<slug:status>', 
         paperhouse.draft_list, name='paperhouse_savedraft_list'),   
    #striker
    path('striker_list_responces/<slug:request_id>', views.striker_list_responces, name='striker_list_responces'),
    path('striker_delete_responces', views.striker_delete_responces, name='striker_delete_responces'),
    path('striker_update_Invoice/<slug:actionrole>', views.striker_update_Invoice, name='striker_update_Invoice'),
    path('striker_update_from_draft/<slug:actionrole>', views.striker_update_from_Draft, name='striker_update_from_draft'),
    
    
    #,path('swagger-docs/', schema_view)
    #,path('docs/', include_docs_urls(title='TSP Billing'))
    
    path('manageaddress', views.manageaddress, name='manageaddress'),
    path('managerate', views.managerate, name='managerate'),
    path('managepayment', views.managepayment, name='managepayment'),
    path('listobjects', views.listobjects, name='listobjects'),
    
    path('listdocs', views.listdocs, name='listdocs'),
    path('list_mailmap_by_status/<slug:status_name>', telegraph.list_mailmap, name='list_mailmap_by_status'),
    path('list_mailmap_by_docid/<slug:docid>', telegraph.list_mailmap, name='list_mailmap_by_docid'),
    path('create_mailmap', telegraph.create_mailmap, name='create_mailmap'),
    path('delete_mailmap/<slug:status_name>', telegraph.delete_mailmap, name='delete_mailmap'),
    path('update_mailmap/<slug:status_name>', telegraph.update_mailmap, name='update_mailmap'),
    
    path('add_wfmobj/<slug:objname>', flexflow.add_wfmobj, name='add_wfmobj'),
    path('list_wfmobj/<slug:objname>', flexflow.list_wfmobj, name='list_wfmobj'),
    path('delete_wfmobj/<slug:objname>/<slug:filter_by_name>', flexflow.delete_wfmobj, name='delete_wfmobj'),
    path('update_wfmobj/<slug:objname>/<slug:filter_by_name>', flexflow.update_wfmobj, name='update_wfmobj'),
    
    path('create_wfdoc/<slug:doctype>', flexflow.create_wfdoc, name='create_wfdoc'),
    path('xluploader_invoice_upload/<slug:wfdoctype>', flexflow.xl_upload, name='xluploader_invoice_upload'),
    path('list_wfdoc/<slug:doctype>', flexflow.list_wfdoc, name='list_wfdoc'),
    path('list_drafts/<slug:doctype>', flexflow.list_drafts, name='list_drafts'),
    path('update_wfdoc/<slug:filter_by_name>', flexflow.update_wfdoc, name='update_wfdoc'),
    path('list_doctypes', flexflow.list_doctypes, name='list_doctypes'),
    path('update_from_draft/<slug:filter_by_name>', flexflow.update_from_draft, name='update_from_draft'),
    path('filtered_list_drafts/<slug:doctype>/<slug:status_name_filter>', flexflow.list_drafts, name='filtered_list_drafts'),
    path('update_selected_fm_drafts', flexflow.update_selected_fm_draft, name='update_selected_fm_drafts'),
    ]



#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/dashboard/urls.py
from django.contrib import admin
from django.urls import path , include
#from rest_framework_swagger.views import get_swagger_view
#from rest_framework.documentation import include_docs_urls

#schema_view = get_swagger_view(title='TSP Billing')



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashapp.urls')),
    #path(r'swagger-docs/', schema_view),
    #path(r'docs/', include_docs_urls(title='TSP Billing')),
]

dashboard/dashapp/models.py
from django.db import models

# Create your models here.

dashboard/dashapp/views.py
import os
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from tokenleaderclient.configs.config_handler import Configs    
from tokenleaderclient.client.client import Client 
from micros1client.client   import MSClient
from linkinvclient.client import LIClient
from django.views.generic.edit import FormView
#from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy
#File Storage
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from werkzeug.utils import secure_filename

from dashapp.tokenleader import tllogin
from dashapp.linkinv import linkinv_views as linkv
from dashapp.tokenleader import tlviews

from dashapp.xluploader import tspinv as xluploadertspinv

from dashapp.penman import penman
from dashapp.paperhouse import paperhouse
from dashapp.striker import striker


def login(request):
    result = tllogin.login(request)
    return result

def log_out(request):
    print("i m inside lout out view")
    template_name, template_data  = tllogin.logout(request)
    return render(request, template_name, template_data)
    
# def home(request):
#     session_user_details = request.session.get('session_user_details')
#     template_data = {"user_details": session_user_details }   
#     result = render(request, 'home.html', template_data)            
#     return result
 
def list_links(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.list_links(request)
    return result
    
def managepayment(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.managepayment(request)
    return result

def managerate(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.managerate(request)
    return result

def manageaddress(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.manageaddress(request)
    return result

def managelocalnet(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.managelocalnet(request)
    return result

def listobjects(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.listobjects(request)
    return result

# TOKENLEADER ======================================

def list_org(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_org(request)
    return result
    		
def add_org(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_org(request)
    return result
    		
def delete_org(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_org(request)
    return result       			

def list_ou(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_ou(request)
    return result

def add_ou(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_ou(request)
    return result   
    		
def delete_ou(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_ou(request)
    return result    

def list_dept(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_dept(request)
    return result
    		
def add_dept(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_dept(request)
    return result
    		    		
def delete_dept(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_dept(request)
    return result  
    		
def list_role(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_role(request)
    return result

def add_role(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_role(request)
    return result
    		
def delete_role(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_role(request)
    return result


def list_users(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_users(request)
    return result

def adduser(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.adduser(request)
    return result
    		
def delete_user(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_user(request)
    return result
    		
def list_wfc(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_wfc(request)
    return result

def add_wfc(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_wfc(request)
    return result
    		
def delete_wfc(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_wfc(request)
    return result
    		
# TOKENLEADER ===========================================



### Divisional Invoice Functionality END
      




def add_service(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.add_service(request)    
    return result

def list_service(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.list_service(request)    
    return result

def delete_service(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = tlviews.delete_service(request)    
    return result


def list_test(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = linkv.list_test(request)  

def home2(request):
    result = render(request, 'home3.html')
    return result

#### Log out
def logout(request):
    if request.session.has_key('uname'):
        del request.session['uname']
    if request.session.has_key('psword'):
        del request.session['psword']
    request.session.clear_expired() 
    result = tllogin.login(request)
    return result
    #result = render(request, "login.html", {'SESSION_EXPIRE':'TRUE'})
    #return result  

######Invoice Model Form Testing
def add_model(request):
 
    if request.method == "POST":
        form = invoiceForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.timestamp = timezone.now()
            model_instance.save()
            return redirect('/') 
    else: 
        form = invoiceForm() 
        return render(request, "home.html", {'CREATE_INVOICE_FORM': form})

 
############### Xluploader #########################################


def xluploader_invoice_upload(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = xluploadertspinv.invoice_upload(request)    
    return result

def download_invoicexlformat(request):
    if 'uname' not in request.session :
        result = logout(request)
    else:
        result = xluploadertspinv.download_invoicexlformat(request)    
    return result


############################# PEN and PAPER House#######################################

def penman_list_events(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = penman.list_events(request)
    return result

def penman_delete_events(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = penman.delete_events(request)
    return result


def penman_delete_event(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = penman.delete_event(request)
    return result



def paperhouse_list_invoice(request, invoicenum, mode, listype):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
        if listype == 'admin':
            result = paperhouse.list_invoices(request, invoicenum, mode, 'admin')
        else:
            result = paperhouse.list_invoices(request, invoicenum, mode)
    return result

# def paperhouse_list_invoice_admin(request):
#     if 'uname' not in request.session :
#       result = login(request)
#     elif 'uname' in request.session :
#       result = paperhouse.list_invoices(request, "admin")
#     return result 

def paperhouse_delete_invoice(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = paperhouse.delete_invoices(request)
    return result

def tsp_list_invoice(request):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = paperhouse.tsp_list_invoices(request)
    return result


def striker_list_responces(request, request_id):
    if 'uname' not in request.session :
      result = login(request)
    elif 'uname' in request.session :
      result = striker.list_exec_status(request, request_id)
    return result


def striker_delete_responces(request):
    if 'uname' not in request.session :

dashboard/dashapp/templates/admin_pages/add_dept.html
{% extends "home.html" %}
{% block content-area %}
{% url 'dashapp:add_dept' as adpt%}
{% url 'dashapp:list_dept' as ldept%}

 <form action="{{ adpt }}" method="post">
      {% csrf_token %}  
        <div class="cotainer">
	        <div class="row justify-content-center">
	           <div class="col-md-8">
                   <div class="card">
                        <div class="card-header">Add New Department</div>
                        <div class="card-body">
	 					    <div class="form-group row">
                             <label for="deptname" class="col-md-4 col-form-label text-sm-right "> Name</label>
                             <div class="col-md-8">
                                 <input type="text" class="form-control input-sm" id="deptname" name="deptname" required >
                             </div>
			             	</div>
			             	 <div class="row">
                                     <div class="col-sm-3">
                <button class="btn btn-sm fa fa-plus"  type="submit"> &nbsp SAVE</button>
            </div>
            <div class="col-sm-5 justify-content-center">     
            </div>
            <div class="col-sm-3 justify-content-end"  >
                <a class="btn  btn-sm fa fa-minus" href="{{ ldept }}"> &nbsp CANCEL</a>
            </div>
                             </div>
			             </div>			                
		             </div>		             
	             </div>
             </div>
        </div>
    
</form>{% endblock content-area %}

<!--  ======================================== CODE ENDs HERE ==========================================    -->

dashboard/dashapp/templates/admin_pages/add_org.html
{% extends "home.html" %}
{% block content-area %}
{% url 'dashapp:add_org' as addorg%}
{% url 'dashapp:list_org' as lorg%}
 <form action="{{ addorg }}" method="post">

     
       
           {% csrf_token %}            
       
 	  <div class="cotainer">
	        <div class="row justify-content-center">
	           <div class="col-md-8">
                   <div class="card">
                        <div class="card-header">Add New Organization</div>
                        <div class="card-body">
	 					    <div class="form-group row">
                             <label for="orgname" class="col-md-4 col-form-label text-sm-right "> Name</label>
                             <div class="col-md-8">
                                 <input type="text" class="form-control input-sm" id="orgname" name="orgname" required >
                             </div>
			             	</div>
			             	 <div class="row">
                                     <div class="col-sm-3">
                <button class="btn btn-sm fa fa-plus"  type="submit"> &nbsp SAVE</button>
            </div>
            <div class="col-sm-5 justify-content-center">     
            </div>
            <div class="col-sm-3 justify-content-end"  >
                <a class="btn  btn-sm fa fa-minus" href="{{ lorg }}"> &nbsp CANCEL</a>
            </div>
                             </div>
			             </div>			                
		             </div>		             
	             </div>
             </div>
        </div>
                                
	 
	
	 
    </form>{% endblock content-area %}


<!--  ======================================== CODE ENDs HERE ==========================================    -->

dashboard/dashapp/templates/admin_pages/add_ou.html
{% extends "home.html" %}
{% block content-area %}
{% url 'dashapp:add_ou' as addou%}
{% url 'dashapp:list_ou' as lou%}
  <form action="{{ addou }}" method="post">

   
    
     {% csrf_token %}  
        <div class="cotainer">
	        <div class="row justify-content-center">
	           <div class="col-md-8">
                   <div class="card">
                        <div class="card-header">Add New Organization Unit</div>
                        <div class="card-body">
	 					    <div class="form-group row">
                             <label for="ouname" class="col-md-4 col-form-label text-sm-right "> Name</label>
                             <div class="col-md-8">
                                 <input type="text" class="form-control input-sm" id="ouname" name="ouname" required >
                             </div>
			             	</div>
			             	 <div class="row">
                                     <div class="col-sm-3">
                <button class="btn btn-sm fa fa-plus"  type="submit"> &nbsp SAVE</button>
            </div>
            <div class="col-sm-5 justify-content-center">     
            </div>
            <div class="col-sm-3 justify-content-end"  >
                <a class="btn  btn-sm fa fa-minus" href="{{ lou }}"> &nbsp CANCEL</a>
            </div>
                             </div>
			             </div>			                
		             </div>		             
	             </div>
             </div>
        </div>
  </form>
    
{% endblock content-area %}


<!--  ======================================== CODE ENDs HERE ==========================================    -->

dashboard/dashapp/templates/admin_pages/general_list.html
{% extends "home.html" %}
{% block content-area %}
{% load getattribute %}
{% url 'dashapp:add_wfmobj'  objname as add_wfmobj %}


    <div class="container-fluid" style="padding-top:7px">
        <h3> List of {{ objname }} </h3>
        {% block add_delete_button %}
            <div class="row">
                <div class="col-sm-3">
                    <a class="btn btn-primary btn-sm fa fa-plus" href="{{ add_wfmobj }}">
                         &nbsp Add {{ objname }}
                     </a>
                </div>
                <div class="col-sm-5 justify-content-center">     
                </div>
                <div class="col-sm-3 justify-content-end"  >
                    <a class="btn  btn-sm fa fa-minus" href="{{ ldept }}"> &nbsp Delete All </a>
                </div>
            </div>

        {% endblock add_delete_button %} 
               
        <table class="table table-striped table-hover">
            <thead >
                <tr style="background-color: #4CAF50;font-size:10px">
                    {% for field_name in objfields %}
	                    <th>{{ field_name }}</th>	                    
	                {% endfor %}
	                <th>edit</th>
	                <th>delete</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list reversed %}
                    <tr style="font-size:10px">      
                        {% for field_name in objfields %}
                            <td>{{ object|getattribute:field_name }}</td>
                        {% endfor %}
                        <td>
                            <a class="fa fa-edit" style="font-size:10px;color:red"  href="{% url 'dashapp:update_wfmobj' objname object.name  %}" ></a>               
                        </td>
                        <td>
                            <a class="fa fa-remove" style="font-size:10px;color:red"  href="{% url 'dashapp:delete_wfmobj' objname object.name  %}" ></a>               
                        </td>
                    </tr>
                {% endfor %}
                  
            </tbody>
        </table>
        <p>{{ result }}</p>
    </div>
    
{% endblock content-area %}


<!--  {'is_active': 'Y', 'otp_mode': 'mail', 'allowemaillogin': 'N', 
        'email': 'prasen.biswas@itc.in', 'created by': 'user1', 
        'wfc': {'is_active': 'Y', 'org': 'org1', 
                 'creation_date': '2019-07-04 15:03:08', 'created by': None, 'name': 'wfc1', 
                 'orgunit': 'ou1', 'id': 1, 'department': 'dept1'}, 
        'username': 'prasen', 'id': 6, 'roles': ['role1'], 'creation_date': '2019-07-08 12:55:16'} -->

dashboard/dashapp/templates/admin_pages/list_role.html
{% extends "home.html" %}
{% block content-area %}
{% url 'dashapp:add_role' as adrole%}
{% url 'dashapp:delete_role' as drole %}
    <div class="container-fluid" style="padding-top:7px">
        <div class="row">
            <div class="col-sm-3">
                <a class="btn btn-primary btn-sm fa fa-plus" href="{{ adrole }}"> &nbsp add new role</a>
            </div>
            <div class="col-sm-7 justify-content-center">
                <h5>List of registered role in tokenleader</h5>
            </div>
            <div class="col-sm-2 justify-content-end">
                <a class="btn btn-danger btn-sm fa fa-minus" href="#"> &nbsp delete all role</a>
            </div> 
        </div>
       
               
        <table class="table table-striped table-hover">
            <thead >
                <tr style="background-color: #4CAF50;font-size:12px">
			        <th>Role Name</th>			        
			        <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for r in list_role.status %}
			      <tr style="font-size:10px">			        
			        <td>{{ r.name}}</td>
			        <td>
			             <form action="{{drole}}" method="POST" 
			                             enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" id="rolename" name="rolename" value="{{r.name}}" 
                                             class="form-control">
                            <button class="fa fa-remove" style="font-size:10px;color:red" 
                                type="submit"  onclick="return confirm('Are you sure? you want to Delete Role')">                                
                            </button>
                    </form>
			        </td> 
			      </tr>
			    {% endfor %}
			</tbody>
		</table>
	</div>
                                                                                                                                                        
{% endblock content-area %}


<!--  {'is_active': 'Y', 'otp_mode': 'mail', 'allowemaillogin': 'N', 
        'email': 'prasen.biswas@itc.in', 'created by': 'user1', 
        'wfc': {'is_active': 'Y', 'org': 'org1', 
                 'creation_date': '2019-07-04 15:03:08', 'created by': None, 'name': 'wfc1', 
                 'orgunit': 'ou1', 'id': 1, 'department': 'dept1'}, 
        'username': 'prasen', 'id': 6, 'roles': ['role1'], 'creation_date': '2019-07-08 12:55:16'} -->

dashboard/dashapp/templates/admin_pages/list_users.html
{% extends "home.html" %}
{% block content-area %}
{% url 'dashapp:adduser' as aduser%}
{% url 'dashapp:delete_user' as duser %}
    <div class="container-fluid" style="padding-top:7px">
        <div class="row">
            <div class="col-sm-3">
                <a class="btn btn-primary btn-sm fa fa-plus" href="{{ aduser }}"> &nbsp add new user</a>
            </div>
            <div class="col-sm-7 justify-content-center">
                <h5>List of registered users in tokenleader</h5>
            </div>
            <div class="col-sm-2 justify-content-end">
                <a class="btn btn-danger btn-sm fa fa-minus" href="#"> &nbsp delete all users</a>
            </div> 
        </div>
               
        <table class="table table-striped table-hover">
            <thead >
                <tr style="background-color: #4CAF50;font-size:10px">
			        <th>Name</th>
			        <th>Email</th>
			        <th>Role</th>
			        <th>Org</th>
			        <th>OU</th>
			        <th>Department</th>
			        <th>Active</th>
			        <th>OTP</th>			        
			        <th>maillogin</th>
			        <th>WFC</th>			        
			        <th>reset pwd</th>
			        <th>unlock</th>
			        <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for l in list_users %}
			      <tr style="font-size:10px">			        
			        <td>{{ l.username }}</td>
			        <td>{{ l.email }}</td>
			        <td>{{ l.roles|join:"," }}</td>
			        <td>{{ l.wfc.org }}</td>
			        <td>{{ l.wfc.orgunit }}</td>
			        <td>{{ l.wfc.dept }}</td>
			        <td>{{ l.is_active }}</td>
			        <td>{{ l.otp_mode }}</td>
			        <td>{{ l.allowemaillogin }}</td>
			        <td>{{ l.wfc.name }}</td>
			        <td>
                         <a href="{% url 'dashapp:reset_password' l.username l.wfc.org %}" >reset</a>
                    </td>
                    <td>
                         <a href="{% url 'dashapp:unlock_user' l.username l.wfc.org %}" >unlock</a>
                    </td>
			        <td>
			             <form action="{{duser}}" method="POST" 
			                             enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" id="username" name="username" value="{{l.username}}" 
                                             class="form-control">
                            <button class="fa fa-remove" style="font-size:10px;color:red" 
                                type="submit"  onclick="return confirm('Are you sure? you want to Delete User')">                                
                            </button>
                    </form>
			        </td>
			      </tr>
			    {% endfor %}
			</tbody>
		</table>
	</div>
    
{% endblock content-area %}


<!--  {'is_active': 'Y', 'otp_mode': 'mail', 'allowemaillogin': 'N', 
        'email': 'prasen.biswas@itc.in', 'created by': 'user1', 
        'wfc': {'is_active': 'Y', 'org': 'org1', 
                 'creation_date': '2019-07-04 15:03:08', 'created by': None, 'name': 'wfc1', 
                 'orgunit': 'ou1', 'id': 1, 'department': 'dept1'}, 
        'username': 'prasen', 'id': 6, 'roles': ['role1'], 'creation_date': '2019-07-08 12:55:16'} -->

dashboard/dashapp/templates/admin_pages/status_modal.html
{% extends "home.html" %}
{% block content-area %}
{% url 'dashapp:list_users' as luser%}
{% url 'dashapp:list_org' as lorg%}
<br>
<div class="container" style="padding-top:10px">
          <h5>Status: 
          {% if STATUS_ADDUSER.status %}
          
          {{ STATUS_ADDUSER.status }}
          
          {% else %}
          {{ status }} 
          {% endif %}
           </h5>
        </div>
        
        <div class="modal-footer">
          <a type="button" class="btn btn-secondary" data-dismiss="modal" href="{{ luser }}">Close</a>
          <a type="button" class="btn btn-secondary" data-dismiss="modal" href="{{ lorg }}">Close</a>
        </div>
</div>
{% endblock content-area %}